### ISSUE TITLE
Providers in Elytron should be registered before security-realms (in /core-service=management)

### ISSUE THREAD

**Issue by kwart** [wildfly-security/elytron-subsystem#145]
After defining SunPKCS11 provider in elytron and adding new security realm with PKCS11 keystore server sometimes starts correctly and sometimes tries use the PKCS11 before it's initialized (i.e. fails with `java.security.NoSuchAlgorithmException: PKCS11 KeyStore not available`)

[This server.log](http://fpaste.org/317514/44251441/) shows both cases - first failed, the second was successfull.

CLI operations used:
```
/subsystem=elytron/provider-loader=NSSfips:add(providers=[{class-names=["sun.security.pkcs11.SunPKCS11"], module="sun.jdk", property-list=[{key="nssModule", value="fips"}, {key="nssSecmodDirectory", value="/home/kwart/test/fips/fipsdb"}, {key="nssLibraryDirectory",value="/usr/lib/x86_64-linux-gnu"}, {key="name", value="testPKCS11"}]}], register=true)

/core-service=management/security-realm=FIPSRealm:add
/core-service=management/security-realm=FIPSRealm/server-identity=ssl:add(keystore-provider=PKCS11, keystore-password=pass123+)
```

**Comment by darranl** [comment]
I am going to go ahead and close this issue, after considering it I don't think this is a valid configuration.

If you are configuring the legacy security realms then providers should be registered as they already are today - i.e. JVM configuration.

If you are making use of Elytron registered providers then you should also be using Elytron SSLContext definitions which are the new unified SSL configuration resources and depend on one of these instead - that way all correct dependencies will be in place.
