### ISSUE TITLE
Permissions have been removed from SecurityIdentity - any way to make them visible?

### ISSUE THREAD

**Issue by darranl** [wildfly-security/elytron-subsystem#166]
The answer may be 'no' but just raising this issue so we can double check if there is an alternative way to represent an identities permissions in the management model.

**Comment by dmlloyd** [comment]
The answer is really "sometimes".  If the authorization policy of the identity is a simple collection of allowed permissions, then calling "toPermissionCollection" on the identity may yield a permission collection that can be examined.  If not, then the policy is more complex (but could probably still be illustrated as a String, though we would need a bit of enhancement to make that happen).

**Comment by darranl** [comment]
Going to close this as invalid for now.  Switching to a PermissionVerifier the notion of an identity having a static set of assigned permissions is quite blurred.

What we may want to consider later is ways to test permissions against an identity but if we are going to provide that kind of dummy testing we probably need a lot more to achieve it than just looking at permissions.
