### ISSUE TITLE
Incorrect description for trust-managers resource.

### ISSUE THREAD

**Issue by darranl** [wildfly-security/elytron-subsystem#209]
"A key manager definition for creating the TrustManager[] as used to create an SSLContext."

Should be 'trust' manager.

**Comment by darranl** [comment]
Also @honza889 would you mind taking a quick look at this one?  I think is a one word fix.

**Comment by honza889** [comment]
Fixed as part of https://github.com/wildfly-security/elytron-subsystem/pull/210
