### ISSUE TITLE
Add operations to add and a new provider to the specific place in the list and to remove specific providers.

### ISSUE THREAD

**Issue by darranl** [wildfly-security/elytron-subsystem#28]
The representation of the providers attribute contains an index that should be used as the basis for this.

**Comment by darranl** [comment]
Marking as ON HOLD as enhancements to management in general will be providing fine grained access to complex attributes within the management model.

The original description may be out of date but additional work may be required within the subsystem to take advantage of these new capabilities.

**Comment by mchoma** [comment]
Hi Darran,

what is the state of this issue. It is crucial for setting wildfly/EAP to run in FIPS mode. Because it is necessary to set SunPKCS11 / IBMJCEFIPS secutiry providers  on the first place.

Martin

**Comment by darranl** [comment]
Currenty on hold - we know we need to come back and rework the provider registrations but for the moment we need to focus on other integration - we did run into a problem RE PKCS#11 and servers restarting so may still need to think things through but still in the TODO list.

**Comment by darranl** [comment]
Going to close this as the resource is being replaced - we will then pick up new issues as they arise in the new impl.
