### ISSUE TITLE
Check why we need the credential store client capability

### ISSUE THREAD

**Issue by darranl** [wildfly-security/elytron-subsystem#285]
Resources should need to add a new capability just to depend on the credential store, instead their own capability should be used.

**Comment by darranl** [comment]
@pskopek Just raising this so we can look at it later, I don't think resources should need a new capability.

**Comment by pskopek** [comment]
I have fix in this branch: https://github.com/pskopek/elytron-subsystem/tree/res-need-not-csc-capability
Just didn't file PR as it needs WF-CORE  3.0.0.Alpha13. The change is already wf-core's master branch.
