### ISSUE TITLE
Add JDBC backed realm definitions.

### ISSUE THREAD

**Issue by darranl** [wildfly-security/elytron-subsystem#46]

**Comment by pedroigor** [comment]
Here are some ideas on how to configure the Jdbc Realm and Password Mappers.

Using one resource for each password type:

```
<jdbc-realm>
    <authentication-query sql="SELECT password FROM CLEAR_PASSWORD_TABLE WHERE username = ?">	
        <clear-password password-column-index="1"/>
    </authentication-query>
</jdbc-realm>
```

Using a single resource for each password type. In this case, we use the `algorithm` attribute to specify the type being mapped:

```
<jdbc-realm>
    <authentication-query sql="SELECT password FROM CLEAR_PASSWORD_TABLE WHERE username = ?">	
        <password algorithm="CLEAR" password-column-index="1"/>
    </authentication-query>
</jdbc-realm>
```

Currently, I'm considering the first option. But it would lead to a more complex resource definition, however with a better usability given that each password type will have its own resource and specific attributes such as cost/iteration count, salt, etc.

**Comment by darranl** [comment]
Actually I think you are mixing concepts here, there doesn't need to be a 100% 1:1 relationship between XML and the resources so the first form of XML illustrated here can always be used.

Child resources become more of an issue for usability when it comes to usability with the CLI, as an example first you execute an operation to add the realm, this goes through stages MODEL and RUNTIME and adds and starts the realms but it has no password mappers defined, next the user manually adds a password mapper.  To make this work as a single operation the user now needs to execute it as a compound operation, we then need to make sure that any MODEL stage validation is deferred until after all the other MODEL stage operations.  So generally usage and maintenance becomes complicated.

How many password type mappers are there?
Can there be multiple instances of different types?
Does ordering of the mappers make a difference?

**Comment by pedroigor** [comment]
Internally, we have a single mapper for all password types (clear, digest, scram, etc). So I would like to represent them with different XML elements (first form). Also, an authentication query may have multiple mappers in case you are able to obtain different key types from a single query.

Ordering does not make any difference.

**Comment by darranl** [comment]
Ok the representation of the different types in XML is fine, a child element in the XML does not have to mean a child resource in the model.

What I would suggest for the management model then is that you define an ObjectTypeDefinition for password-mapper - this type will then contain attributes for clear-mapper, digest-mapper etc... each of these will be an ObjectTypeDefinition with the appropriate fields - that way you will have strong typing in the management model and at the same time allow zero or one definitions of each mapper type.

**Comment by pedroigor** [comment]
Yeah, that is what I'm doing now.
